version: "3.8"

services:
  backend:
    image: chrisfarrugiamt/css2425backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: veterinary-clinic-nginx
    ports:
      - "80:80"
    volumes:
      - ./dist/veterinary-clinic/browser:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
